### ISSUE TITLE
Line Items is always an empty array

### ISSUE THREAD

**Issue by st-bobb** [QubitProducts/UniversalVariable-Magento-Extension#52]
Line Items in the Basket is not getting populated on our production servers.
This was an issue for us in the beginning. We commented out the check for visibility in _getLineItems of Uv.php. That apparently solved it for a while(at least we saw it locally) and now it has popped up again. 
We cannot confirm that Qubit ever saw line items on production.
The UV basket does get line items on my local machine.
Our production servers use Varnish and we have 5 to 8 servers running at any one time.
We use the turpentine Magento extension.
Any thoughts an how to get that data to show up in the UV much appreciated.

**Comment by rogy** [comment]
Having no UV line items is normally caused by these caching extensions, so that sounds like it is your problem.
We don't have generic solution for this because these extensions work in different ways, and have different methods of cache busting. It should be possible for you to exclude the UV extension blocks from being cached, What affect this will have on performance will have to be played with.

Thanks

**Comment by st-bobb** [comment]
We can close this. We use grouped products so we comment out the check for visible items. We do this in our theme. Copied the path /app/code/local/QuBit/UniversalVariable/Model/Uv.php into our theme on my mac. Qubit(lower case b). Mac doesn't care Linux does. Not even the first time we have made this mistake!!
